### ISSUE TITLE
Empty profile

### ISSUE THREAD

**Issue by stgleb** [uber/go-torch#46]
Maybe it is not directly related to your product, but when i'm trying to fetch profile from my app
i get an error that profile is empty(empty when using torch or go tool pprof either).

Code running pprof http server

https://github.com/stgleb/top_words/blob/7304a94/main.go#L19

I just simpi run 

`go-torch`

And get

`INFO[19:12:45] Run pprof command: go tool pprof -raw -seconds 2 http://localhost:8080/debug/pprof/profile
FATA[19:12:47] Failed: could not get raw output from pprof: pprof error: exit status 1
STDERR:
Fetching profile from http://localhost:8080/debug/pprof/profile?seconds=2
Please wait... (2s)
Saved profile in /home/gstepanov/pprof/pprof.main.localhost:8080.samples.cpu.014.pb.gz
profile is empty
`

Could you tell when i do something wrong?

**Comment by prashantv** [comment]
Hi @stgleb,

The error is coming from pprof itself which happens if your application was not doing much hence the profile was empty. This will happen regardless of whether go-torch is used or not.

pprof is a stack sampling profiler, which means it stops the program some number of times per second (by default, 100), and looks at what is running on the CPU. If you profile for 2 seconds, it would have stopped the program ~200 times, looked at what's running and recorded it.

If your program has no load, it's possible there's nothing running, so the profile is empty since there was nothing running everytime pprof stopped to program to check what was running.

Make sure that you are putting some load on your program, or that it's doing something, otherwise you will get an empty pprof.

You might want to read more about profiling here: https://blog.golang.org/profiling-go-programs

**Comment by sandlerben** [comment]
It doesn't seem like your application is doing anything while you are profiling. A pprof profile takes a sample of the function calls over a period of time. Since you server is just waiting for a request, nothing would show up in the profile.

**Comment by sandlerben** [comment]
Exactly what Prashant said

**Comment by stgleb** [comment]
Thanks a lot!
